### ISSUE TITLE
TokyoWesterns CTF - Asterisk-Alloc

### ISSUE THREAD

**Issue by Jorgecmartins** [balsn/ctf_writeup#7]
Why doing realloc(-1, 'a') makes realloc get a chunk of tcache next time its called, realloc(0x90, 'a')

Thanks

**Comment by st424204** [comment]
If realloc fails to allocate the requested block of memory, a null pointer is returned, and the original memory block will not be freed.
We force realloc failed to return NULL to get chance malloc a new memory block.
Because the original memory is not free, we will get a chunk from tcache with same size.
